// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Rhuan Patriky",
            "url": "https://linktr.ee/rhuanpk",
            "email": "support@rhuanpk.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/address": {
            "get": {
                "description": "List all addresses.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "address"
                ],
                "summary": "LIST",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "TOKEN",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.AddressList"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new address.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "address"
                ],
                "summary": "CREATE",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "TOKEN",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Json request.",
                        "name": "JSON",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AddressCreate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.AddressList"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            },
            "delete": {
                "description": "Permanently delete many or all address.",
                "tags": [
                    "address"
                ],
                "summary": "DELETE",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "TOKEN",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "csv",
                        "description": "Address ID's.",
                        "name": "addresses",
                        "in": "query"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            }
        },
        "/address/client/{client}": {
            "get": {
                "description": "Lists all addresses for a client.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "address"
                ],
                "summary": "LIST",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "TOKEN",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Client ID.",
                        "name": "client",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.AddressList"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            }
        },
        "/address/{address}": {
            "get": {
                "description": "Get a single address from ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "address"
                ],
                "summary": "GET",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "TOKEN",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Address ID.",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AddressList"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            },
            "delete": {
                "description": "Permanently delete an address.",
                "tags": [
                    "address"
                ],
                "summary": "DELETE",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "TOKEN",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Address ID.",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update already existing address.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "address"
                ],
                "summary": "UPDATE",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "TOKEN",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Json request.",
                        "name": "JSON",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AddressUpdate"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "Address ID.",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            }
        },
        "/address/{address}/client/{client}": {
            "get": {
                "description": "Get a single address for a single client from your ID's.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "address"
                ],
                "summary": "GET",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "TOKEN",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Address ID.",
                        "name": "address",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Client ID.",
                        "name": "client",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AddressList"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            }
        },
        "/auth": {
            "get": {
                "description": "Get user ID inside the token (JWT).",
                "tags": [
                    "auth"
                ],
                "summary": "ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "TOKEN",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            },
            "post": {
                "description": "Log-in and get a authentication token (JWT).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "LOGIN",
                "parameters": [
                    {
                        "description": "Json request.",
                        "name": "JSON",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Auth"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Token"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            }
        },
        "/client": {
            "get": {
                "description": "List all clients only.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "LIST",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "TOKEN",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Bring the inactive ones.",
                        "name": "inactives",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ClientList"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new client.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "CREATE",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "TOKEN",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Json request.",
                        "name": "JSON",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ClientCreate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.ClientList"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deactivate many or all clients.",
                "tags": [
                    "client"
                ],
                "summary": "DELETE",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "TOKEN",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "csv",
                        "description": "Client ID's.",
                        "name": "clients",
                        "in": "query"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            }
        },
        "/client/addresses": {
            "get": {
                "description": "List all clients with all addresses.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "LIST",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "TOKEN",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ClientList"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            }
        },
        "/client/{client}": {
            "get": {
                "description": "Get a single client from ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "GET",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "TOKEN",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Client ID.",
                        "name": "client",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ClientList"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deactivate a single client.",
                "tags": [
                    "client"
                ],
                "summary": "DELETE",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "TOKEN",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Client ID.",
                        "name": "client",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update already existing client.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "UPDATE",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "TOKEN",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Json request.",
                        "name": "JSON",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ClientUpdate"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "Client ID.",
                        "name": "client",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            }
        },
        "/client/{client}/address/{address}": {
            "get": {
                "description": "Get a single client with a single address from your ID's.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "GET",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "TOKEN",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Client ID.",
                        "name": "client",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Address ID.",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ClientList"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            }
        },
        "/client/{client}/addresses": {
            "get": {
                "description": "List a single client with all addresses.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "LIST",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "TOKEN",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Client ID.",
                        "name": "client",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ClientList"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            }
        },
        "/order": {
            "get": {
                "description": "List all Orders.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order"
                ],
                "summary": "LIST",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.OrderList"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new order.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order"
                ],
                "summary": "CREATE",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "TOKEN",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Json request.",
                        "name": "JSON",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.OrderCreate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.OrderList"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deactivate many or all orders.",
                "tags": [
                    "order"
                ],
                "summary": "DELETE",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "csv",
                        "description": "Order ID's.",
                        "name": "orders",
                        "in": "query"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            }
        },
        "/order/{order}": {
            "get": {
                "description": "Get a single order from ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order"
                ],
                "summary": "GET",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "TOKEN",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Order ID.",
                        "name": "order",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.OrderList"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deactivate a single order.",
                "tags": [
                    "order"
                ],
                "summary": "DELETE",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Order ID.",
                        "name": "order",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update already existing order.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "order"
                ],
                "summary": "UPDATE",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Order ID.",
                        "name": "order",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Json request.",
                        "name": "JSON",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.OrderUpdate"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            }
        },
        "/service": {
            "get": {
                "description": "List all services.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "LIST",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Bring the inactive ones.",
                        "name": "inactives",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ServiceList"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new service.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "CREATE",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "TOKEN",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Json request.",
                        "name": "JSON",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ServiceCreate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.ServiceList"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deactivate many or all services.",
                "tags": [
                    "service"
                ],
                "summary": "DELETE",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "csv",
                        "description": "Service ID's.",
                        "name": "services",
                        "in": "query"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            }
        },
        "/service/{service}": {
            "get": {
                "description": "Get a single service from ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "GET",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "TOKEN",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Service ID.",
                        "name": "service",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ServiceList"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deactivate a single service.",
                "tags": [
                    "service"
                ],
                "summary": "DELETE",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Service ID.",
                        "name": "service",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update already existing service.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "UPDATE",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Service ID.",
                        "name": "service",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Json request.",
                        "name": "JSON",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ServiceUpdate"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            }
        },
        "/user": {
            "get": {
                "description": "List all users.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "LIST",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Bring the inactive ones.",
                        "name": "inactives",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.UserList"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "CREATE",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "TOKEN",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Json request.",
                        "name": "JSON",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserCreate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.UserList"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deactivate many or all user.",
                "tags": [
                    "user"
                ],
                "summary": "DELETE",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "csv",
                        "description": "User ID's.",
                        "name": "users",
                        "in": "query"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            }
        },
        "/user/{user}": {
            "get": {
                "description": "Get a single user from ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "GET",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "TOKEN",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "User ID.",
                        "name": "user",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserList"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deactivate a single user.",
                "tags": [
                    "user"
                ],
                "summary": "DELETE",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "User ID.",
                        "name": "user",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update already existing user.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "UPDATE",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token.",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "User ID.",
                        "name": "user",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Json request.",
                        "name": "JSON",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserUpdate"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTP"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AddressCreate": {
            "type": "object",
            "required": [
                "district",
                "number",
                "street"
            ],
            "properties": {
                "city": {
                    "type": "string"
                },
                "client_id": {
                    "type": "integer"
                },
                "district": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                },
                "state": {
                    "type": "string"
                },
                "street": {
                    "type": "string"
                }
            }
        },
        "models.AddressList": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string"
                },
                "client_id": {
                    "type": "integer"
                },
                "district": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "number": {
                    "type": "integer"
                },
                "state": {
                    "type": "string"
                },
                "street": {
                    "type": "string"
                }
            }
        },
        "models.AddressUpdate": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                },
                "state": {
                    "type": "string"
                },
                "street": {
                    "type": "string"
                }
            }
        },
        "models.Auth": {
            "type": "object",
            "required": [
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 8
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.ClientCreate": {
            "type": "object",
            "required": [
                "addresses",
                "document",
                "name",
                "phone"
            ],
            "properties": {
                "addresses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.AddressCreate"
                    }
                },
                "document": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "integer"
                }
            }
        },
        "models.ClientList": {
            "type": "object",
            "properties": {
                "addresses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.AddressList"
                    }
                },
                "document": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "integer"
                }
            }
        },
        "models.ClientUpdate": {
            "type": "object",
            "properties": {
                "document": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "integer"
                }
            }
        },
        "models.HTTP": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "models.OrderCreate": {
            "type": "object",
            "required": [
                "client_id",
                "service_id",
                "user_id"
            ],
            "properties": {
                "client_id": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "service_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.OrderList": {
            "type": "object",
            "properties": {
                "client": {
                    "$ref": "#/definitions/models.ClientList"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "service": {
                    "$ref": "#/definitions/models.ServiceList"
                },
                "user": {
                    "$ref": "#/definitions/models.UserList"
                }
            }
        },
        "models.OrderUpdate": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "service_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.ServiceCreate": {
            "type": "object",
            "required": [
                "service"
            ],
            "properties": {
                "service": {
                    "type": "string"
                }
            }
        },
        "models.ServiceList": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "service": {
                    "type": "string"
                }
            }
        },
        "models.ServiceUpdate": {
            "type": "object",
            "properties": {
                "service": {
                    "type": "string"
                }
            }
        },
        "models.Token": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "models.UserCreate": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 8
                },
                "role": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.UserList": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.UserUpdate": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0.0",
	Host:             "localhost:8008",
	BasePath:         "/api/v2",
	Schemes:          []string{},
	Title:            "Benlimp API",
	Description:      "API for Benlimp project.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
